- name: Create 'wheel' user group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add sudoers users to wheel group
  become: yes
  user: name=siwapp groups=wheel append=yes state=present createhome=yes

# - name: Set up authorized keys for the deployer user
#   authorized_key: user=siwapp key="{{item}}"
#   with_file:
#     - id_rsa.pub
